#ifndef _DPD_ERR_CODES_T_H
#define _DPD_ERR_CODES_T_H

#define DPD_ERROR_CODE_START    (0xE0 << 8u)    /*!< 0xE000 - Starting error code */

typedef enum dpd_ErrCode
{
    DPD_ERR_CODE_NO_ERROR           =   0U,
    DPD_CHOL_SOLVER_ERROR           =   (DPD_ERROR_CODE_START + 0x01U),
    DPD_MODEL_DESCRIPTOR_ERROR      =   (DPD_ERROR_CODE_START + 0x02U),
    DPD_MODEL_DDR_DELAY_ERROR       =   (DPD_ERROR_CODE_START + 0x03U),
    DPD_MODEL_POLY_TYPE_ERROR       =   (DPD_ERROR_CODE_START + 0x04U),
    DPD_MODEL_INVALID_ERROR         =   (DPD_ERROR_CODE_START + 0x05U),
    DPD_MODEL_DUPLICATE_LUT_ERROR   =   (DPD_ERROR_CODE_START + 0x06U),
    DPD_FEATURE_COMPUTE_ERROR       =   (DPD_ERROR_CODE_START + 0x07U),
    DPD_MAX_FRAC_EST_CNT_ERROR      =   (DPD_ERROR_CODE_START + 0x08U),
    DPD_ACT_LUT_ENTRY_SAT_ERROR     =   (DPD_ERROR_CODE_START + 0x09U),
    DPD_SAMPLE_POINTER_NULL_ERROR   =   (DPD_ERROR_CODE_START + 0x0AU),
    DPD_LUT_COPY_FAILED_ERROR       =   (DPD_ERROR_CODE_START + 0x0BU),
    DPD_MEMORY_APPLY_ERROR          =   (DPD_ERROR_CODE_START + 0x0CU),
    DPD_SEARCH_REF_ERROR            =   (DPD_ERROR_CODE_START + 0x0DU),
	DPD_CAPTURE_ORX_ERROR			= 	(DPD_ERROR_CODE_START + 0x0EU),
	DPD_CAPTURE_TU_ERROR			= 	(DPD_ERROR_CODE_START + 0x0FU),
	DPD_CAPTURE_TX_ERROR			= 	(DPD_ERROR_CODE_START + 0x10U),

    DPD_HW_MEM_DEVICE_OPEN_ERROR	=	(DPD_ERROR_CODE_START + 0xF0U),
    DPD_HW_MEM_DEVICE_UNINTED_ERROR	=	(DPD_ERROR_CODE_START + 0xF1U),
    DPD_HW_MEM_MAP_ERROR	        =	(DPD_ERROR_CODE_START + 0xF2U),
    DPD_HW_MEM_UNMAP_ERROR	        =	(DPD_ERROR_CODE_START + 0xF3U),
    DPD_UNKNOWN_ERROR               =   0x8000U
} dpd_ErrCode_e;

#endif
